from . import payments
from . import start
from . import info
from . import party
from . import names
from . import settings_profile
from . import edites
from . import support
from . import adminpanel